// Copyright Zero Games. All Rights Reserved.

#include "Export/ZExportEnums.h"

ZSHARP_BEGIN_EXPORT_ENUM(ENetMode, false)
	ZSHARP_EXPORT_ENUM_VALUE(NM_Standalone)
	ZSHARP_EXPORT_ENUM_VALUE(NM_DedicatedServer)
	ZSHARP_EXPORT_ENUM_VALUE(NM_ListenServer)
	ZSHARP_EXPORT_ENUM_VALUE(NM_Client)
	ZSHARP_EXPORT_ENUM_VALUE(NM_MAX)
ZSHARP_END_EXPORT_ENUM(ENetMode)

ZSHARP_BEGIN_EXPORT_ENUM_EX(EWorldType::Type, false, EWorldType)
	ZSHARP_EXPORT_ENUM_VALUE(None)
	ZSHARP_EXPORT_ENUM_VALUE(Game)
	ZSHARP_EXPORT_ENUM_VALUE(Editor)
	ZSHARP_EXPORT_ENUM_VALUE(PIE)
	ZSHARP_EXPORT_ENUM_VALUE(EditorPreview)
	ZSHARP_EXPORT_ENUM_VALUE(GamePreview)
	ZSHARP_EXPORT_ENUM_VALUE(GameRPC)
	ZSHARP_EXPORT_ENUM_VALUE(Inactive)
ZSHARP_END_EXPORT_ENUM_EX(EWorldType::Type, EWorldType)


