// Copyright Zero Games. All Rights Reserved.

using System.Xml.Linq;

namespace ZeroGames.ZSharp.Build.Solution;

public static class XmlHelper
{

	public static XDocument MakeDocument()
	{
		XDocument doc = new();
		
		doc.Add(new XComment(
@"*************************************************
Copyright Zero Games. All Rights Reserved.

IMPORTANT: THIS FILE IS GENERATED BY Z#. DO NOT MODIFY DIRECTLY!
*************************************************"));

		return doc;
	}
	
}


