// Copyright Zero Games. All Rights Reserved.

using System.Text;

namespace ZeroGames.ZSharp.Build.Glue;

public class MiscWriter
{
	
	public MiscWriter(ExportedMisc misc, string directory)
	{
		_misc = misc;
		_codeDir = directory;
	}

	public void Write()
	{
		WriteCollisionProfile();
	}

	private void WriteCollisionProfile()
	{
		StringBuilder sb = new();
		sb.Append(HEADER);

		sb.Append(
@"using ZeroGames.ZSharp.UnrealEngine.CoreUObject;

namespace ZeroGames.ZSharp.UnrealEngine.Engine;

public static class CollisionProfiles
{
");

		foreach (var profile in _misc.CollisionProfiles)
		{
			sb.Append($"\tpublic static readonly FName {profile} = nameof({profile});\n");
		}

		sb.Append("}\n\n");
		
		sb.Append(END);
		
		using StreamWriter sw = new(File.Create($"{_codeDir}/CollisionProfiles.cs"), Encoding.UTF8);
		sw.Write(sb.ToString());
	}
	
	private const string HEADER =
@"// Copyright Zero Games. All Rights Reserved.

// IMPORTANT: THIS FILE IS GENERATED BY Z#. DO NOT MODIFY DIRECTLY!

#region GENERATED CODE

";

	private const string END =
@"#endregion


";

	private readonly ExportedMisc _misc;
	private readonly string _codeDir;

}


