// Copyright Zero Games. All Rights Reserved.


#include "Conjugate/ZObjectWrapperConjugateRegisties.h"

#include "Conjugate/ZDeclareConjugateRegistryMacros.h"

ZSHARP_DECLARE_CONJUGATE_REGISTRY(FZConjugateRegistry_SubclassOf)
ZSHARP_DECLARE_CONJUGATE_REGISTRY(FZConjugateRegistry_SoftClassPtr)
ZSHARP_DECLARE_CONJUGATE_REGISTRY(FZConjugateRegistry_SoftObjectPtr)
ZSHARP_DECLARE_CONJUGATE_REGISTRY(FZConjugateRegistry_WeakObjectPtr)
ZSHARP_DECLARE_CONJUGATE_REGISTRY(FZConjugateRegistry_LazyObjectPtr)
ZSHARP_DECLARE_CONJUGATE_REGISTRY(FZConjugateRegistry_ScriptInterface)


