// Copyright Zero Games. All Rights Reserved.

/* Add 'THIS FILE IS GENERATED BY ZSHARP!' for generated code */
/* Add 'DO NOT MODIFY DIRECTLY!' for generated code */

/* Add '#region GENERATED CODE' for generated code */

namespace ZeroGames.ZSharp.UnrealEngine.ExportExample; /* Namespace = AssemblyName + ModuleName */

/* Add an attribute [ZeroGames.ZSharp.UnrealEngine.Export.Intrinsic] for user provided glue, [ZeroGames.ZSharp.UnrealEngine.Export.Generated] for generated glue. */
public class PlainUnmanagedClassExportedObjectExample /* Class name can be customized */
    : ZeroGames.ZSharp.UnrealEngine.Export.PlainUnmanagedClassExportedObjectBase /* Inherit from this if no base class */
    , ZeroGames.ZSharp.Core.IConjugate<PlainUnmanagedClassExportedObjectExample> /* Implement IConjugate<> to provide factory */
{
    
    public static PlainUnmanagedClassExportedObjectExample BuildConjugate(IntPtr unmanaged)
    {
        throw new NotImplementedException();
    }

    protected override void ReleaseUnmanagedResource()
    {
        throw new NotImplementedException();
    }
    
}

/* Add '#endregion' for generated code */


