// Copyright Zero Games. All Rights Reserved.

#pragma once

#define ZSHARP_ENABLE_CONJUGATE_UNSAFE 1
#define ZSHARP_ENABLE_CONJUGATE_UNSAFE_FAST ZSHARP_ENABLE_CONJUGATE_UNSAFE && 1
#define ZSHARP_TREATS_BLACK_CONJUGATE_AS_GC_OBJECT 1


