// Copyright Zero Games. All Rights Reserved.

using System.Text;

namespace ZeroGames.ZSharp.Build.Glue;

public class DelegateWriter : IDisposable, IAsyncDisposable
{

	public DelegateWriter(ExportedDelegate exportedDelegate, Stream stream)
	{
		_exportedDelegate = exportedDelegate;
		_sw = new(stream, Encoding.UTF8);
	}

	public void Dispose()
	{
		_sw.Dispose();
	}

	public async ValueTask DisposeAsync()
	{
		await _sw.DisposeAsync();
	}

	public Task WriteAsync() => Task.Run(() =>
	{
		string returnType = _exportedDelegate.ReturnParameter?.Type.ToString() ?? "void";
		string delegateName = _exportedDelegate.Name.Split('.')[^1];
		string parameterList = "";
		string delegateDeclaration = $"public delegate {returnType} {delegateName}({parameterList});";
		if (_exportedDelegate.Name.Contains('.'))
		{
			string outerClassName = _exportedDelegate.Name.Split('.')[0];
			delegateDeclaration =
$@"public partial class {outerClassName}
{{
	{delegateDeclaration}
}}";
		}
		
		_sw.Write(
			@$"// Copyright Zero Games. All Rights Reserved.

// THIS FILE IS GENERATED BY ZSHARP.
// DO NOT MODIFY DIRECTLY!

#region GENERATED CODE

#nullable enable

namespace {_exportedDelegate.Namespace};

{delegateDeclaration}

#endregion


");
	});

	private ExportedDelegate _exportedDelegate;
	private StreamWriter _sw;
	
}