// Copyright Zero Games. All Rights Reserved.

using System.Text;

namespace ZeroGames.ZSharp.Build.Glue;

public class EnumWriter : IDisposable, IAsyncDisposable
{

	public EnumWriter(ExportedEnum exportedEnum, Stream stream)
	{
		_exportedEnum = exportedEnum;
		_sw = new(stream, Encoding.UTF8);
	}

	public void Dispose()
	{
		_sw.Dispose();
	}

	public async ValueTask DisposeAsync()
	{
		await _sw.DisposeAsync();
	}

	public Task WriteAsync() => Task.Run(() =>
	{
		_sw.Write(
@$"// Copyright Zero Games. All Rights Reserved.

// THIS FILE IS GENERATED BY ZSHARP.
// DO NOT MODIFY DIRECTLY!

#region GENERATED CODE

namespace {_exportedEnum.Namespace};

[System.CodeDom.Compiler.GeneratedCode(""ZSharp"", ""0.0.1"")]
public enum {_exportedEnum.Name} : {_exportedEnum.UnderlyingType}
{{
{_enumBody}
}}

#endregion


");
	});

	private string _enumBody
	{
		get
		{
			StringBuilder enumBody = new();
			bool first = true;
			foreach (var pair in _exportedEnum.ValueMap)
			{
				if (!first)
				{
					enumBody.Append('\n');
				}
				else
				{
					first = false;
				}

				enumBody.Append($"\t{pair.Key} = {pair.Value},");
			}

			return enumBody.ToString();
		}
	}

	private ExportedEnum _exportedEnum;
	private StreamWriter _sw;
	
}


